spring.application.name=ClinicaVeterinaria
spring.datasource.url=jdbc:mysql://localhost:3306/clinicaVeterinaria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
# Usamos la clase moderna del dialecto (o puedes eliminar esta línea y Hibernate lo detecta solo)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect