spring.application.name=JPA
# Ajusta el nombre de la BD, usuario y clave según tu instalación local de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/prueba_jpa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
# Usamos la clase moderna del dialecto (o puedes eliminar esta línea y Hibernate lo detecta solo)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect